"""empty message

Revision ID: 9b94c21ae9d6
Revises: 84998d279f5b
Create Date: 2024-02-19 11:18:34.394933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b94c21ae9d6'
down_revision = '84998d279f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_power', schema=None) as batch_op:
        batch_op.drop_constraint('_hero_power_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_power', schema=None) as batch_op:
        batch_op.create_unique_constraint('_hero_power_uc', ['hero_id', 'power_id'])

    # ### end Alembic commands ###
